### PR TITLE
Kube state metrics

### PR DESCRIPTION
**Pull request by DreadPirateShawn**
Custom normalization for kube-state-metrics.

Note -- I wasn't sure how you'd like to handle the kapacitor config. It's not included in the original project (which makes sense) but since we're adding UDFs, those **do** need to be called out in the config, so I though that was worth capturing somewhere.

### CODE REVIEW

**Comment by nathanielc** [comment]
@DreadPirateShawn Thanks for the PR! Can you provide an example of how the metrics are joined? i.e. the raw values and then the joined values. 

It would be best if we can avoid the complexity of a UDF and the default template is quite flexible so it may be possible to do what you want in pure TICKscript. If not I'd love to have a discussion around how we could improve things.

Thanks again!

**Comment by DreadPirateShawn** [comment]
Sure!

Here's the logic behind both of our UDFs...

**UDF 1: group_consolidate_true_false_unknown.py**

One of the data sets provided by kube-state-metrics looks like this:

```
# HELP kube_node_status_disk_pressure Whether the kubelet is under pressure due to insufficient available disk.
# TYPE kube_node_status_disk_pressure gauge
kube_node_status_disk_pressure{condition="false",node="kube-master1"} 1
kube_node_status_disk_pressure{condition="true",node="kube-master1"} 0
kube_node_status_disk_pressure{condition="unknown",node="kube-master1"} 0
# HELP kube_node_status_memory_pressure Whether the kubelet is under pressure due to insufficient available memory.
# TYPE kube_node_status_memory_pressure gauge
kube_node_status_memory_pressure{condition="false",node="kube-master1"} 1
kube_node_status_memory_pressure{condition="true",node="kube-master1"} 0
kube_node_status_memory_pressure{condition="unknown",node="kube-master1"} 0
# HELP kube_node_status_out_of_disk Whether the node is out of disk space
# TYPE kube_node_status_out_of_disk gauge
kube_node_status_out_of_disk{condition="false",node="kube-master1"} 1
kube_node_status_out_of_disk{condition="true",node="kube-master1"} 0
kube_node_status_out_of_disk{condition="unknown",node="kube-master1"} 0
# HELP kube_node_status_ready The ready status of a cluster node.
# TYPE kube_node_status_ready gauge
kube_node_status_ready{condition="false",node="kube-master1"} 0
kube_node_status_ready{condition="true",node="kube-master1"} 1
kube_node_status_ready{condition="unknown",node="kube-master1"} 0
```

That is -- the same data point, "is node X in a 'Y' status?" is answered three times:
* is node X status Y=true? 1
* is node X status Y=false? 0
* is node X status Y=unknown? 0

| name | condition | node | value |
| --- | --- | --- | --- |
| kube_node_status_disk_pressure | true | kube-master1 | 0 |
| kube_node_status_disk_pressure | false | kube-master1 | 1 |
| kube_node_status_disk_pressure | unknown | kube-master1 | 0 |
| kube_node_status_memory_pressure | true | kube-master1 | 0 |
| kube_node_status_memory_pressure | false | kube-master1 | 1 |
| kube_node_status_memory_pressure | unknown | kube-master1 | 0 |
| kube_node_status_out_of_disk | true | kube-master1 | 0 |
| kube_node_status_out_of_disk | false | kube-master1 | 1 |
| kube_node_status_out_of_disk | unknown | kube-master1 | 0 |
| kube_node_status_ready | true | kube-master1 | 1 |
| kube_node_status_ready | false | kube-master1 | 0 |
| kube_node_status_ready | unknown | kube-master1 | 0 |

What we need is to convert each set of three entries into a single field "node_status_Y" with a true/false/unknown value. (We debated strings vs ints here, and went with ints b/c it seems a bit purer.)

| name | node | value |
| --- | --- | --- |
| kube_node_status_disk_pressure | kube-master1 | 0 |
| kube_node_status_memory_pressure | kube-master1 | 0 |
| kube_node_status_out_of_disk | kube-master1 | 0 |
| kube_node_status_ready | kube-master1 | 1 |

This is what we came up with in pure TICKscript, before we switched to the UDF:

```
var measurement = 'kube_node_status'
var metric_prefix = measurement + '_'

var exclude = ['__name__']
var flatten_on = exclude
var drop_field_name = TRUE

stream
    |from()
    |default().tag('condition', '')
    |where(lambda: strHasPrefix("__name__", measurement) AND strLength("condition") > 0 AND int("value") == 1)
    |eval(lambda: strTrimPrefix("__name__", metric_prefix))
        .as('__name__')
        .tags('__name__')
        .keep('value')
    |eval(lambda: if("condition" == 'true', 1, if("condition" == 'false', 0, -1)))
        .as('value')
        .keep('value')
    |delete()
        .tag('condition')
    |groupBy(*)
        .exclude(exclude)
    |flatten()
        .on(flatten_on)
        .dropOriginalFieldName(drop_field_name)
```

Some of our concerns with this:
1) Much harder to reuse between TICKscripts -- eg "kube_nodes" and "kube_pods" both include this same data pattern, and the chain of nodes involved seemed unwieldy to clearly track.
2) Chaining -- this requires a `where(lambda: strHasPrefix("__name__", 'kube_node_status')`, which means that in order to gather **all** "kube_node_*" data points together, we needed to have one TICKscript which queried for 'kube_node_status' conditions and normalized those, and then another which joined the output of this TICKscript into the larger data set.

Speaking of gathering all "kube_node_*" data points together, that segues to the second UDF:

**UDF 2: group_consolidate_true_false_unknown.py**

Here we ran into a different issue. Starting with the raw examples in prometheus_metrics_normalizer, we had a TICKscript like so:

```
stream
    |from()
        .where(lambda: strHasPrefix("__name__", metric_prefix))
    |eval(lambda: strTrimPrefix("__name__", metric_prefix))
        .as('__name__')
        .tags('__name__')
        .keep('value')
    |groupBy(*)
        .exclude(exclude)
    |flatten()
        .on(flatten_on)
        .dropOriginalFieldName(drop_field_name)
    |kapacitorLoopback()
        .database(db)
        .retentionPolicy(rp)
        .measurement(measurement)
```

However, the tag variation between measurements made this tick script untenable. For example, given these sample pod metrics:

```
...
# HELP kube_pod_info Information about pod.
# TYPE kube_pod_info gauge
kube_pod_info{created_by="ReplicationController/bar",host_ip="192.168.0.2",namespace="foo",node="minion1",pod="bar-skjs8",pod_ip="10.1.2.3"} 1
...
# HELP kube_pod_status_phase The pods current phase.
# TYPE kube_pod_status_phase gauge
kube_pod_status_phase{namespace="foo",phase="Running",pod="bar-skjs8"} 1
...
# HELP kube_pod_status_ready Describes whether the pod is ready to serve requests.
# TYPE kube_pod_status_ready gauge
kube_pod_status_ready{condition="false",namespace="foo",pod="bar-skjs8"} 0
kube_pod_status_ready{condition="true",namespace="foo",pod="bar-skjs8"} 1
kube_pod_status_ready{condition="unknown",namespace="foo",pod="bar-skjs8"} 0
…
```
...all describing a single pod, the simple TICKscript above would result in something like the following entries for a given timestamp:

| pod | namespace | created_by | host_ip | node | pod_ip | phase | ready | value |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  bar-skjs8 | foo | ReplicaSet/bar | 192.168.0.2 | minion1 | 10.1.2.3 |   |   | 1 |
| bar-skjs8 | foo |   |   |   |   | Running |   | 1 |
| bar-skjs8 | foo |   |   |   |   |   | false | 0 |
| bar-skjs8 | foo |   |   |   |   |   | true | 1 |
| bar-skjs8 | foo |   |   |   |   |   | unknown | 0 |

Granted, the false/true/unknown processing step makes this slightly better -- but still doesn't actually join all the pod data together.

For instance, selecting from that data set where "phase='Running'" will not give results with the relevant node of such a pod -- even though we clearly *have* that data, the original tags are different and so the data isn't joined.

What we need is this:

| pod | namespace | created_by | host_ip | node | pod_ip | phase | ready | value |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| bar-skjs8 | foo | ReplicaSet/bar | 192.168.0.2 | minion1 | 10.1.2.3 | Running | 1 | 1 |

The `flatten` node was originally what we attempted to use here, but according to the documentation (and our experimentation), it doesn't do the transformation described above.

That is, when we flattened blindly, then all unique tags disappear from the result. No dice.

When we flattened and specified a tag that's present on some of the data, eg "host_ip", then we get steady errors that "host_ip" is missing from points -- and where host_ip **is** present, it causes a separate tag for each distinct host_ip value, eg separate tags for "info.192.168.0.13.value" and "info.192.168.0.6.value".

We speculated that we could achieve what we wanted with a giant TICKscript which included an eval for every known tag, and fancy logic to group/gather/rename each one -- but this wouldn't be reusable between our TICKscripts at all, which seemed like a Really Awkward Idea. (And even then, we weren't convinced it would work coherently.)

Whereas with the UDF approach, we have a couple dozen lines of reusable logic (namely the `process` method, since the rest is largely boilerplate) and can easily perform the same process in all TICKscripts, without knowing anything about the specific tags. (Technically we do include the option to ignore/drop certain tags, but that's just for courtesy cleanup -- those aren't strictly required.)

**Summary**

We'd love to have a more native TICKscript implementation here -- hopefully something easily reusable between the TICKscripts, and something that allows a single TICKscript chain to handle "all kube_node_* data" (for instance) -- that is, both the true/false/unknown consolidation and the general tag/field consolidation.

Perhaps there were options that we missed? (or misunderstood?)

**Comment by nathanielc** [comment]
@DreadPirateShawn Thanks for the thorough explanation! I think I understand the transformations you needed and why you needed UDFs. 

What follows is my attempt and explaining what you needed and framing it to be the more generic operators you needed.

## True/False/Unknown

This problem is essentially converting a set of mutually exclusive boolean values to an enumeration. So if we had a node in TICKscript like boolsToEnumeration that has parameters of a single tag name and then mapped the tag values to the field value. This would mean using strings but would work generically for any set of mutually exclusive set of boolean values.

Something like
```
|boolsToEnumeration()
   .tag('condition')
```

## Joining to a Single point

Here what you needed was simply a way to take several points and return a single point that was the union of the fields and tags of the set of points. Maybe we call it `merge` for now. All current nodes do not do this. The current join node doesn't do this because it expects to join different streams of data, not multiple points from the same stream. The union node is about creating a union of streams of data, not a union of points. The flatten node is about flattening a set of points along a certain dimension. 

So if we were to create a new `merge` node it could simply merge a set of points into a single point.


## Summary 

Is my understanding correct? If so I have a few questions/suggestions:

How is your Go, would you consider converting your UDFs into first class nodes in TICKscript? 

The merge node makes a lot of sense. The boolsToEnumeration seems quite specialized but I see why its needed and do not see another simpler way to perform that operation generically(i.e. for an arbitrary number of enumeration values) 


That said I think accepting this PR with the UDFs for now is a good first step as it allows people to get up and running with this data. 

I do have some feedback on the current state of the PR.

Mainly the use of `cycle_time` and batch. As I read the code the UDF is operating in batch mode so that it can get a snapshot of all points created for a single scrape cycle. A window node uses a `cycle_time` value less than the scrape interval so as to create a batch of points that are all from the same scrape cycle. There is a simpler way to do this using stream and eliminating the need for the window. All points from a single scrape will have the exact same time, so you can have the UDF accept stream data and buffer all the points that have the same time, then when  a new point arrives that has a different time then you know to process the current buffer and add the new point to a new empty buffer. This way you can decouple the scripts for the configuration of the scrape interval as the UDF will work for any scrape interval.

**Comment by DreadPirateShawn** [comment]
@nathanielc

## Re: True/False/Unknown

That sounds about right...

Although, as a top-level node, I assume one would need to filter the stream down to the specific metric in question first, eg `.where(lambda: strHasPrefix("__name__", metric_prefix))` -- which I think means we'd then need to re-join the stream back into the rest of the data?

With the current UDF approach, it's kinda functioning like so:

    |boolsToEnumeration()
       .where(lambda: strHasPrefix("__name__", metric_prefix))
       .tag('condition')

...such that the resulting stream still contains both the target metric and the rest of the metrics too.

So perhaps this node could/should behave like `where`, which can function as both a top-level node `|where` and also as a sub-node `|from.where`? Specifically I'm thinking of our use case, where we want to join all related metrics and also perform this boolean conversion.

## Re: Joining to a Single point

Correct. Glad we weren't simply overlooking something!

## Re: Go, converting UDFs into first class nodes in TICKscript

I'm definitely interested. (My Go is in the intermediate realm -- I'd be reluctant to drive a project from scratch but am comfortable working within an established project.)

I'll just need to schedule this work-wise -- my manager is on board, so it's likely just a matter of timing.

So if you're in a rush then "we'll see," otherwise "yes." :-)

## Re: accepting this PR with the UDFs for now is a good first step

Excellent!

## Re: `cycle_time` vs batch vs stream

Oooh, buffering the stream is a great idea here... let me check that out -- assuming it works as envisioned, I'll plan to update the pull request (probably tomorrow).

**Comment by nathanielc** [comment]
> So if you're in a rush then "we'll see," otherwise "yes." :-)

No rush here, I would just like to progress towards being able to perform this transformation in native TICKscript. We will be happy to help out with direction etc when needed.

As for the boolsToEnumeration agreed that it is helpful to pass the data through that you do not care to immediately process, so you can process the data linearly instead of via splits and joins. Not sure how to best do that but we have time to discuss and arrive at a good solution.

Looking forward to the updated PR :)

**Comment by DreadPirateShawn** [comment]
Pull request has been updated.

**Comment by DreadPirateShawn** [comment]
Is there anything else that you'd like to change before we merge this? No worries if it's just in the queue, I'm not in a rush -- just touching base.

**Review by nathanielc — APPROVED** [review]

**Pull request merged**
